//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 + 支持的版本:3.1, 3.2, 3.2.50, 3.3, 与 gc-toolkit/RSAPatch 保持同步。 的本地化字符串。
        /// </summary>
        public static string about_desp {
            get {
                return ResourceManager.GetString("about_desp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在运行 的本地化字符串。
        /// </summary>
        public static string btn_running {
            get {
                return ResourceManager.GetString("btn_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动搜索 的本地化字符串。
        /// </summary>
        public static string btn_searchgame {
            get {
                return ResourceManager.GetString("btn_searchgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动选择 的本地化字符串。
        /// </summary>
        public static string btn_selectgame {
            get {
                return ResourceManager.GetString("btn_selectgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始游戏 的本地化字符串。
        /// </summary>
        public static string btn_startgame {
            get {
                return ResourceManager.GetString("btn_startgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启代理 的本地化字符串。
        /// </summary>
        public static string btn_startproxy {
            get {
                return ResourceManager.GetString("btn_startproxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭代理 的本地化字符串。
        /// </summary>
        public static string btn_stopproxy {
            get {
                return ResourceManager.GetString("btn_stopproxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启调试 的本地化字符串。
        /// </summary>
        public static string cb_enabledebug {
            get {
                return ResourceManager.GetString("cb_enabledebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用http 的本地化字符串。
        /// </summary>
        public static string cb_usehttp {
            get {
                return ResourceManager.GetString("cb_usehttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string cm_add {
            get {
                return ResourceManager.GetString("cm_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string cm_del {
            get {
                return ResourceManager.GetString("cm_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string cm_edit {
            get {
                return ResourceManager.GetString("cm_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到剪贴板 的本地化字符串。
        /// </summary>
        public static string cm_export {
            get {
                return ResourceManager.GetString("cm_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从剪贴板导入 的本地化字符串。
        /// </summary>
        public static string cm_import {
            get {
                return ResourceManager.GetString("cm_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string h_about {
            get {
                return ResourceManager.GetString("h_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发 的本地化字符串。
        /// </summary>
        public static string h_develop {
            get {
                return ResourceManager.GetString("h_develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string h_general {
            get {
                return ResourceManager.GetString("h_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器编辑 的本地化字符串。
        /// </summary>
        public static string h_serveredit {
            get {
                return ResourceManager.GetString("h_serveredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用服务器： 的本地化字符串。
        /// </summary>
        public static string h_servers {
            get {
                return ResourceManager.GetString("h_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string nav_about {
            get {
                return ResourceManager.GetString("nav_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string nav_home {
            get {
                return ResourceManager.GetString("nav_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string nav_setting {
            get {
                return ResourceManager.GetString("nav_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [感谢]:https://github.com/34736384/RSAPatch 的本地化字符串。
        /// </summary>
        public static string repo1 {
            get {
                return ResourceManager.GetString("repo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [开源地址]:https://github.com/gc-toolkit/Launcher 的本地化字符串。
        /// </summary>
        public static string repoinfo {
            get {
                return ResourceManager.GetString("repoinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级 的本地化字符串。
        /// </summary>
        public static string t_advanced {
            get {
                return ResourceManager.GetString("t_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官方 的本地化字符串。
        /// </summary>
        public static string tab_official {
            get {
                return ResourceManager.GetString("tab_official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有 的本地化字符串。
        /// </summary>
        public static string tab_private {
            get {
                return ResourceManager.GetString("tab_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅代理 的本地化字符串。
        /// </summary>
        public static string tab_proxyonly {
            get {
                return ResourceManager.GetString("tab_proxyonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string tb_ok {
            get {
                return ResourceManager.GetString("tb_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景图片 的本地化字符串。
        /// </summary>
        public static string tbtip_bgurl {
            get {
                return ResourceManager.GetString("tbtip_bgurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏路径 的本地化字符串。
        /// </summary>
        public static string tbtip_gamepath {
            get {
                return ResourceManager.GetString("tbtip_gamepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经有一个启动器在运行 的本地化字符串。
        /// </summary>
        public static string tip_alreadyrunning {
            get {
                return ResourceManager.GetString("tip_alreadyrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置正确的游戏路径！ 的本地化字符串。
        /// </summary>
        public static string tip_correctgamepath {
            get {
                return ResourceManager.GetString("tip_correctgamepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 崩溃了 的本地化字符串。
        /// </summary>
        public static string tip_crash_title {
            get {
                return ResourceManager.GetString("tip_crash_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功！ 的本地化字符串。
        /// </summary>
        public static string tip_exp_succ {
            get {
                return ResourceManager.GetString("tip_exp_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败！ 的本地化字符串。
        /// </summary>
        public static string tip_imp_err {
            get {
                return ResourceManager.GetString("tip_imp_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功！ 的本地化字符串。
        /// </summary>
        public static string tip_imp_succ {
            get {
                return ResourceManager.GetString("tip_imp_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在不能开始游戏！ 的本地化字符串。
        /// </summary>
        public static string tip_nostart {
            get {
                return ResourceManager.GetString("tip_nostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrivateKey,为空则禁用 的本地化字符串。
        /// </summary>
        public static string tip_privatekey {
            get {
                return ResourceManager.GetString("tip_privatekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PublicKey,为空则选择割草机的key 的本地化字符串。
        /// </summary>
        public static string tip_publickey {
            get {
                return ResourceManager.GetString("tip_publickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少添加并选择一个服务器！ 的本地化字符串。
        /// </summary>
        public static string tip_reqaddone {
            get {
                return ResourceManager.GetString("tip_reqaddone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个服务器！ 的本地化字符串。
        /// </summary>
        public static string tip_reqselectone {
            get {
                return ResourceManager.GetString("tip_reqselectone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索失败，注册表中没有相关信息！ 的本地化字符串。
        /// </summary>
        public static string tip_search_err {
            get {
                return ResourceManager.GetString("tip_search_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个服务器 的本地化字符串。
        /// </summary>
        public static string tip_selectone {
            get {
                return ResourceManager.GetString("tip_selectone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已找到位于{0}的游戏文件! 的本地化字符串。
        /// </summary>
        public static string tip_serach_succ {
            get {
                return ResourceManager.GetString("tip_serach_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先设置 游戏目录 和 游戏版本！ 的本地化字符串。
        /// </summary>
        public static string tip_setcfg {
            get {
                return ResourceManager.GetString("tip_setcfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器名称 的本地化字符串。
        /// </summary>
        public static string tip_srvname {
            get {
                return ResourceManager.GetString("tip_srvname", resourceCulture);
            }
        }
    }
}
